name: flutter_sample
repository: https://github.com/nogal2/flutter-sample.git

packages:
  - packages/*

command:
  version:
    includeCommitId: true
  bootstrap:
    hooks:
      post: |
        flutter pub run melos build_runner:build
scripts:
  lint:all:
    run: |
      flutter pub run melos run lint:analyze && \
      flutter pub run melos run lint:format
  lint:analyze:
    run: |
      flutter pub run melos exec -- \
      flutter analyze . --fatal-infos
  lint:format:
    run: |
      flutter pub run melos exec -- \
      dart format . --output=none --set-exit-if-changed
  test:all:
    run: |
      flutter pub run melos run test:unit
  test:unit:
    run: |
      flutter pub run melos exec --depends-on="test" -- \
      dart test &&
      flutter pub run melos exec --depends-on="flutter_test" -- \
      flutter test
    packageFilters:
      dirExists:
        - test
  build_runner:build:
    run: |
      flutter pub run melos exec --depends-on="build_runner" --scope="*core*" -- \
      flutter pub run build_runner build --delete-conflicting-outputs &&
      flutter pub run melos exec --depends-on="build_runner" --ignore="*core*" -- \
      flutter pub run build_runner build --delete-conflicting-outputs
  build_runner:watch:
    run: |
      flutter pub run melos build_runner:build &&
      flutter pub run melos exec --depends-on="build_runner" -- \
      flutter pub run build_runner watch --delete-conflicting-outputs
